# Конфиг воркера-счётчика UnlockMyLoot.
# НЕ менять id KV — там хранится текущее значение opened.
name = "unlockmyloot"
main = "counter-worker.js"
compatibility_date = "2026-06-01"

routes = [
  { pattern = "api.unlockmyloot.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "COUNTER"
id = "4d93f48984724c4d87a1158e99257356"
